export const habitatImages: Record<string, string> = {
  dornbuschland: '/habitats/dornbuschland-sketch-transparent-6963fcccb9.png',
  feldflur: '/habitats/feldflur-sketch-transparent-c623e98eaf.png',
  felsen: '/habitats/felsen-sketch-transparent-2b9808dcbd.png',
  gebirge: '/habitats/gebirge-sketch-transparent-d9b1fecb8a.png',
  gewaesser: '/habitats/gewaesser-sketch-transparent-e246ca063f.png',
  inseln: '/habitats/inseln-sketch-transparent-5079639c76.png',
  kueste: '/habitats/kueste-sketch-transparent-dbfee0aba2.png',
  park: '/habitats/park-sketch-transparent-79299a16dd.png',
  regenwald: '/habitats/regenwald-sketch-transparent-c03a86f433.png',
  savanne: '/habitats/savanne-sketch-transparent-02e45cf385.png',
  stadt: '/habitats/stadt-sketch-transparent-95cd7b14c8.png',
  steppe: '/habitats/steppe-sketch-transparent-3c20ffa083.png',
  tundra: '/habitats/tundra-sketch-transparent-e64676fa8e.png',
  wald: '/habitats/wald-sketch-transparent-cb120a1ded.png',
};
