// Generated by scripts/build-range-maps.mjs from attributed geographic data.
export const rangeBasemapUrl = '/maps/world-6061b211e8c5.json';
export type RangeMapEntry = {
  url: string;
  taxonId: number;
  scientificName: string;
  modelVersion: string;
  downloadedOn: string;
  sourceUrl: string;
  datasetUrl: string;
  licenseUrl: string;
  referenceUrl: string;
};
export const rangeMaps: Partial<Record<string, RangeMapEntry>> = {
  rotschwanzbussard: {
    url: '/maps/rotschwanzbussard-97bc9e4d397f.json',
    taxonId: 5212,
    scientificName: 'Buteo jamaicensis',
    modelVersion: '2.33',
    downloadedOn: '2026-09-06',
    sourceUrl:
      'https://inaturalist-open-data.s3.us-east-1.amazonaws.com/geomodel/geojsons/latest/5212.geojson',
    datasetUrl: 'https://www.inaturalist.org/pages/range_maps',
    licenseUrl: 'https://www.inaturalist.org/pages/range_maps',
    referenceUrl:
      'https://www.allaboutbirds.org/guide/Red-tailed_Hawk/maps-range',
  },
  weisskopfseeadler: {
    url: '/maps/weisskopfseeadler-d7f3ca237692.json',
    taxonId: 5305,
    scientificName: 'Haliaeetus leucocephalus',
    modelVersion: '2.33',
    downloadedOn: '2026-09-07',
    sourceUrl:
      'https://inaturalist-open-data.s3.us-east-1.amazonaws.com/geomodel/geojsons/latest/5305.geojson',
    datasetUrl: 'https://www.inaturalist.org/pages/range_maps',
    licenseUrl: 'https://www.inaturalist.org/pages/range_maps',
    referenceUrl: 'https://www.allaboutbirds.org/guide/Bald_Eagle/maps-range',
  },
  koenigsbussard: {
    url: '/maps/koenigsbussard-12d3d08056d0.json',
    taxonId: 5181,
    scientificName: 'Buteo regalis',
    modelVersion: '2.33',
    downloadedOn: '2026-09-07',
    sourceUrl:
      'https://inaturalist-open-data.s3.us-east-1.amazonaws.com/geomodel/geojsons/latest/5181.geojson',
    datasetUrl: 'https://www.inaturalist.org/pages/range_maps',
    licenseUrl: 'https://www.inaturalist.org/pages/range_maps',
    referenceUrl:
      'https://www.allaboutbirds.org/guide/Ferruginous_Hawk/maps-range',
  },
};
