// Generated by scripts/build-range-maps.mjs from attributed geographic data.
export const rangeBasemapUrl = '/maps/world-ac0c5172434b.json';
export const rangeMaps: Record<
  string,
  { url: string; taxonId: number; scientificName: string; modelVersion: string }
> = {
  rotschwanzbussard: {
    url: '/maps/rotschwanzbussard-97bc9e4d397f.json',
    taxonId: 5212,
    scientificName: 'Buteo jamaicensis',
    modelVersion: '2.33',
  },
};
