// Generated by scripts/build-reference-range-maps.mjs.
import type { DisplayRangeMapEntry } from './range-map-entry';
export const referenceRangeMaps: Partial<Record<string, DisplayRangeMapEntry>> =
  {
    habicht: {
      url: '/maps/habicht-reference-19d8f7685823.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:AccipiterGentilis.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    maeusebussard: {
      url: '/maps/maeusebussard-reference-7300e16b188c.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:ButeoButeoIUCN2019_1.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    wanderfalke: {
      url: '/maps/wanderfalke-reference-bccbc1944619.json',
      label: 'Verbreitung',
      sourceName: 'Nach MPF',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:PeregrineRangeMap.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    },
    turmfalke: {
      url: '/maps/turmfalke-reference-d3c888c0424e.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:FalcoTinnunculusIUCNver2019-2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    steinadler: {
      url: '/maps/steinadler-reference-38699ac9d9a9.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:AquilaChrysaetosIUCNver2018_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    seeadler: {
      url: '/maps/seeadler-reference-5876789ae15f.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:HaliaeetusAlbicillaIUCN.svg',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    fischadler: {
      url: '/maps/fischadler-reference-49bf1f300a55.json',
      label: 'Verbreitung',
      sourceName: 'Nach Zoologist und chris',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Pandion_global_range.svg',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
      note: 'Vorlage umfasst Westlichen und Östlichen Fischadler.',
    },
    kaiseradler: {
      url: '/maps/kaiseradler-reference-51642391279b.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:AquilaHeliacaIUCNver2019_1.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    wespenbussard: {
      url: '/maps/wespenbussard-reference-4ad83c397435.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:PernisApivorusIUCN2018_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    bartgeier: {
      url: '/maps/bartgeier-reference-f50ed991e535.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:GypaetusBarbatusIUCNver2018_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    uhu: {
      url: '/maps/uhu-reference-b519f3b972e9.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:BuboBuboIUCN.svg',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    schwarzmilan: {
      url: '/maps/schwarzmilan-reference-423bee8ebf50.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:MilvusMigransIUCNver2018_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      note: 'Vorlage umfasst auch den Gelbschnabelmilan.',
    },
    rotmilan: {
      url: '/maps/rotmilan-reference-ea8d18e69927.json',
      label: 'Verbreitung',
      sourceName: 'Nach Ulrich prokop',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Milvus_milvus_distr02.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    gerfalke: {
      url: '/maps/gerfalke-reference-ea614d2bf0f9.json',
      label: 'Verbreitung',
      sourceName: 'Nach Scops',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Falco_rusticolus_distr.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
    },
    sakerfalke: {
      url: '/maps/sakerfalke-reference-1256da7abe92.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:FalcoCherrugIUCN2019_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    lannerfalke: {
      url: '/maps/lannerfalke-reference-4b2ecee0decf.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:FalcoBiarmicusIUCN2019-3.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    baumfalke: {
      url: '/maps/baumfalke-reference-0c3a78bc8468.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:FalcoSubbuteoIUCNver2019_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    weissstorch: {
      url: '/maps/weissstorch-reference-2b53d2121e52.json',
      label: 'Verbreitung',
      sourceName: 'Nach Shyamal',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:WhiteStorkMap.svg',
      license: 'CC0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
    },
    sperber: {
      url: '/maps/sperber-reference-1fa5bb07a35e.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:AccipiterNisusIUCNver2018_2.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    wuestenbussard: {
      url: '/maps/wuestenbussard-reference-049edd3c8c69.json',
      label: 'Verbreitung',
      sourceName: 'Nach Izvora',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Parabuteo_unicinctus_range_map.png',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
    },
    steppenadler: {
      url: '/maps/steppenadler-reference-be7083ceebee.json',
      label: 'Verbreitung',
      sourceName: 'Nach Alexander Kürthy',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:AquilaNipalensis.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    },
    sekretaer: {
      url: '/maps/sekretaer-reference-77b30633ff0e.json',
      label: 'Verbreitung',
      sourceName: 'Nach Aa77zz',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Secretarybird_distribution_map.svg',
      license: 'CC0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
    },
    andenkondor: {
      url: '/maps/andenkondor-reference-3a7d3100f206.json',
      label: 'Verbreitung',
      sourceName: "Nach Hey jude, don't let me down",
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:AndeanMap.png',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
    },
    kronenadler: {
      url: '/maps/kronenadler-reference-5394a25567b1.json',
      label: 'Verbreitung',
      sourceName: 'Nach Jonathan Hornung',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Stephanoaetus_coronatus_distribution_map_big.png',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
    },
    riesenseeadler: {
      url: '/maps/riesenseeadler-reference-bf2b34e2d2af.json',
      label: 'Verbreitung',
      sourceName: 'Nach Ulrich Prokop (Scops)',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Haliaeetus_pelagicus_distr.png',
      license: 'CC BY-SA 2.5',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/2.5',
      note: 'Küstengebiete; Brut- und Wintervorkommen zusammengefasst.',
    },
    gaukler: {
      url: '/maps/gaukler-reference-38c3202f75d9.json',
      label: 'Verbreitung',
      sourceName: 'Nach Jonathan Hornung',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Gaukler_Terathopius_ecaudatus_world.png',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
    },
    aguja: {
      url: '/maps/aguja-reference-0894d8553d66.json',
      label: 'Verbreitung',
      sourceName: 'Nach Izvora',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Geranoaetus_melanoleucus_range_map.PNG',
      license: 'Public domain',
      licenseUrl: 'https://commons.wikimedia.org/wiki/Commons:Public_domain',
      note: 'Generalisierte Kartenvorlage.',
    },
    falklandkarakara: {
      url: '/maps/falklandkarakara-reference-d888a1d8e8fa.json',
      label: 'Verbreitung',
      sourceName: 'Nach Cephas',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Phalcoboenus_australis_map.svg',
      license: 'CC BY-SA 4.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    },
    schopfkarakara: {
      url: '/maps/schopfkarakara-reference-1455396483fa.json',
      label: 'Verbreitung',
      sourceName: 'Nach MPF',
      sourceUrl: 'https://commons.wikimedia.org/wiki/File:Caracara_map.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
      note: 'Beide Unterarten; ohne den ausgestorbenen Guadalupekarakara.',
    },
    harpyie: {
      url: '/maps/harpyie-reference-79808ad72880.json',
      label: 'Verbreitung',
      sourceName: 'Nach Ninjatacoshell; Cocoloi (Vorlage)',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Harpy_Eagle_Range.svg',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
      note: 'Fehlerhafte Trinidad-Angabe der Vorlage korrigiert.',
    },
    kampfadler: {
      url: '/maps/kampfadler-reference-4bb8e4f64049.json',
      label: 'Verbreitung',
      sourceName: 'Nach Helmy oved',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Polemaetus_bellicosus_distribution_map.svg',
      license: 'CC0',
      licenseUrl: 'https://creativecommons.org/publicdomain/zero/1.0/deed.en',
    },
    virginiauhu: {
      url: '/maps/virginiauhu-reference-d26851ff38d6.json',
      label: 'Verbreitung',
      sourceName: 'Nach Manedwolf; Achim Raschka (Vorlage)',
      sourceUrl:
        'https://commons.wikimedia.org/wiki/File:Bubo_virginianus_dis.png',
      license: 'CC BY-SA 3.0',
      licenseUrl: 'https://creativecommons.org/licenses/by-sa/3.0/',
      note: 'Ohne den als eigene Art geführten Magellanuhu.',
    },
  };
