import type { AdditionalBird } from './additional-birds.ts';

/** Sources and media review: docs/species-additions-20260913.md. */
export const speciesAdditions: AdditionalBird[] = [
  {
    id: 'schleiereule',
    name: 'Schleiereule',
    latin: 'Tyto alba',
    aliases: ['Western Barn Owl', 'Barn Owl'],
    group: 'Eulen',
    tile: null,
    span: [85, 95],
    length: [33, 39],
    weight: [290, 460],
    intro: 'Mit herzförmigem Gesichtsschleier gleitet sie in der Dämmerung über Wiesen und Feldränder.',
    habitat: 'Offenes Kulturland mit Wiesen, Weiden und Säumen. Scheunen, Kirchtürme und andere Gebäude bieten geschützte Brutplätze.',
    range: 'Europa, Afrika & Westasien',
    colors: [['Cremeweiß', '#EEE7D4'], ['Goldbraun', '#BB955D'], ['Silbergrau', '#A4A3A0'], ['Dunkelbraun', '#584638']],
    source: 'https://vogelschutz-tg.ch/projekte/schleiereulen/',
    sourceName: 'BirdLife Thurgau',
    regions: ['Europa', 'Afrika', 'Asien'],
    habitatGroup: 'Offenes Kulturland',
    genusLabel: 'Schleiereulen',
    plumageNotes: {
      male: 'Herzförmiger heller Gesichtsschleier, dunkle Augen und goldgraue Oberseite. Die Unterseite reicht von weiß bis rostbeige; die Geschlechter überlappen in Färbung und Fleckung.',
      female: 'Häufig stärker gefleckt und wärmer gefärbt als das Männchen, aber mit großer Überschneidung. Hier ist eine helle europäische Färbung dargestellt.',
      juvenile: 'Flügge Jungvögel ähneln den Altvögeln bereits stark. Ihr erstes vollständiges Federkleid ist frisch; die Färbung allein erlaubt keine sichere Altersbestimmung.',
    },
    juvenileColors: [['Cremeweiß', '#EEE7D4'], ['Goldbraun', '#BB955D'], ['Silbergrau', '#A4A3A0']],
    bodyColors: {
      male: { eyes: [['Dunkelbraun', '#302921']], legs: [['Graurosa', '#B4A298']] },
      female: { eyes: [['Dunkelbraun', '#302921']], legs: [['Graurosa', '#B4A298']] },
      juvenile: { eyes: [['Dunkelbraun', '#302921']], legs: [['Graurosa', '#B4A298']] },
    },
    hunt: {
      title: 'Mäusejagd nach Gehör',
      text: 'Im niedrigen Suchflug oder von einem Ansitz aus ortet sie Kleinsäuger. Ihr Gesichtsschleier unterstützt das Richtungshören; mit leisem Anflug und vorgestreckten Fängen greift sie zu.',
    },
  },
  {
    id: 'gaensegeier',
    name: 'Gänsegeier',
    latin: 'Gyps fulvus',
    aliases: ['Gaensegeier', 'Griffon Vulture', 'Eurasian Griffon'],
    group: 'Geier',
    tile: null,
    span: [230, 265],
    length: [95, 110],
    weight: [6000, 9000],
    intro: 'Auf breiten Schwingen kreist er über offenen Landschaften und sucht nach verendeten Tieren.',
    habitat: 'Offenes Weideland und Gebirge mit Felswänden und Schluchten als Brut- und Ruheplätze.',
    range: 'Südeuropa, Nordafrika & Asien',
    colors: [['Sandbraun', '#B79A72'], ['Graubraun', '#89775E'], ['Schwarzbraun', '#352F29'], ['Cremeweiß', '#E7DDC8']],
    source: 'https://seo.org/ave/buitre-leonado/',
    sourceName: 'SEO/BirdLife',
    regions: ['Europa', 'Afrika', 'Asien'],
    habitatGroup: 'Gebirge & Felsen',
    genusLabel: 'Gänsegeier',
    plumageNotes: {
      male: 'Helle Halskrause, hornfarbener Schnabel und sandbraune Flügeldecken über dunklen Schwungfedern. Die Geschlechter sind ähnlich gefärbt.',
      female: 'Gleiches Alterskleid wie beim Männchen; am Gefieder lassen sich die Geschlechter kaum unterscheiden.',
      juvenile: 'Dunkleres, rötlich braunes Gefieder mit hellen Schaftstrichen. Halskrause braun und strähnig, Schnabel und Iris dunkel.',
    },
    juvenileColors: [['Rotbraun', '#96704D'], ['Dunkelbraun', '#4B3C2E'], ['Sandbeige', '#C2A57D']],
    bodyColors: {
      male: { eyes: [['Bernstein', '#B59450']], legs: [['Grau', '#8D8980']] },
      female: { eyes: [['Bernstein', '#B59450']], legs: [['Grau', '#8D8980']] },
      juvenile: { eyes: [['Dunkelbraun', '#43372B']], legs: [['Grau', '#8D8980']] },
    },
    hunt: {
      title: 'Aassuche im Segelflug',
      text: 'Mit der Thermik gewinnt er Höhe und sucht weite Flächen ab. Entdeckt ein Geier einen Kadaver, folgen häufig weitere. Mit dem langen Hals erreicht er die weichen Teile im Inneren.',
    },
  },
  {
    id: 'schreiseeadler',
    name: 'Schreiseeadler',
    latin: 'Icthyophaga vocifer',
    aliases: ['Haliaeetus vocifer', 'African Fish Eagle', 'African Fish-Eagle'],
    group: 'Adler',
    tile: null,
    span: [175, 210],
    length: [63, 77],
    weight: [2100, 3600],
    intro: 'Sein weit tragender Ruf begleitet die Seen und Flüsse Afrikas südlich der Sahara.',
    habitat: 'Fischreiche Seen, Flüsse und Feuchtgebiete mit hohen Ansitzbäumen, örtlich auch Küsten und Lagunen.',
    range: 'Afrika südlich der Sahara',
    colors: [['Weiß', '#EEECE3'], ['Kastanienbraun', '#87482E'], ['Schwarzbraun', '#302C28']],
    source: 'https://animaldiversity.org/accounts/Haliaeetus_vocifer/',
    sourceName: 'Animal Diversity Web',
    regions: ['Afrika'],
    habitatGroup: 'Seen & Küsten',
    genusLabel: 'Fischseeadler',
    plumageNotes: {
      male: 'Weißer Kopf, Hals, obere Brust und Schwanz; kastanienbrauner Bauch und schwarze Schwungfedern. Das Weibchen ist ähnlich gefärbt.',
      female: 'Gleiches weiß-kastanienbraunes Alterskleid wie beim Männchen, im Durchschnitt jedoch größer und schwerer.',
      juvenile: 'Überwiegend braun mit unregelmäßigen hellen Flecken an Brust, Flügeln und Schwanz. Das Gesicht ist noch matt graubraun.',
    },
    juvenileColors: [['Dunkelbraun', '#4B3B2D'], ['Braun', '#8C7357'], ['Cremeweiß', '#DFD5BD']],
    bodyColors: {
      male: { eyes: [['Dunkelbraun', '#493729']], legs: [['Gelb', '#D6B24F']] },
      female: { eyes: [['Dunkelbraun', '#493729']], legs: [['Gelb', '#D6B24F']] },
      juvenile: { eyes: [['Dunkelbraun', '#493729']], legs: [['Blassgelb', '#C8BA83']] },
    },
    hunt: {
      title: 'Fischfang an der Oberfläche',
      text: 'Von einem Ansitz oder im Flug entdeckt er Fische nahe der Oberfläche. Er greift mit vorgestreckten Fängen zu; schwere Fische zieht er ans Ufer. Gelegentlich raubt er anderen Vögeln die Beute.',
    },
  },
];
