import {
  readdir,
  readFile,
  writeFile,
  mkdir,
  stat,
  unlink,
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../', import.meta.url));
const publicDir = path.join(root, 'public');
const output = path.join(publicDir, 'optimized');
// Favicons and the share image must stay PNG at fixed URLs; never convert them.
const icons = path.join(publicDir, 'icons');
await mkdir(output, { recursive: true });

// Every image is written at several widths so the browser can pick the
// smallest file that still covers the pixels it paints. The largest rung
// matches what shipped before, so nothing ever loses detail: a bird drawn
// full-bleed on a dense screen still gets the full-resolution encode.
const widthLadder = [320, 560, 900, 1400];
// Head portraits are never drawn larger than a small avatar.
const portraitLadder = [160, 280];
// Quality stays where it was: these illustrations are the point of the site.
// Encoder effort stays at 4 because Netlify rebuilds every image from scratch
// on each deploy, and 6 traded ten minutes of build time for about 3% of bytes.
const options = { quality: 88, alphaQuality: 100, effort: 4 };

async function imagesIn(directory) {
  const result = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const filename = path.join(directory, entry.name);
    if (filename === output || filename === icons) continue;
    if (entry.isDirectory()) result.push(...(await imagesIn(filename)));
    else if (/\.(png|jpe?g)$/i.test(entry.name)) result.push(filename);
  }
  return result;
}

const files = (await imagesIn(publicDir)).sort();
const mapping = {};
let before = 0;
let after = 0;
let cursor = 0;
sharp.concurrency(2);
await Promise.all(
  Array.from({ length: 3 }, async () => {
    while (cursor < files.length) {
      const source = files[cursor++];
      const bytes = await readFile(source);
      const ladder = path.basename(source).startsWith('portrait-')
        ? portraitLadder
        : widthLadder;
      // `rotate()` applies EXIF orientation, so ask sharp for the dimensions
      // it will actually produce rather than trusting the stored header.
      const upright = sharp(bytes).rotate();
      const { width: sourceWidth } = await upright.metadata();
      const ceiling = Math.min(ladder[ladder.length - 1], sourceWidth ?? 0);
      const widths = [...new Set(ladder.filter((w) => w < ceiling).concat(ceiling))]
        .filter((w) => w > 0)
        .sort((a, b) => a - b);
      const variants = [];
      for (const width of widths) {
        const digest = createHash('sha256')
          .update(JSON.stringify({ width, options, sharp: sharp.versions }))
          .update(bytes)
          .digest('hex')
          .slice(0, 16);
        const name = `${path.parse(source).name}-${digest}-${width}.webp`;
        const destination = path.join(output, name);
        try {
          await stat(destination);
        } catch {
          await sharp(bytes)
            .rotate()
            .resize({
              width,
              height: width,
              fit: 'inside',
              withoutEnlargement: true,
            })
            .webp(options)
            .toFile(destination);
        }
        variants.push({ width, url: `/optimized/${name}` });
        after += (await stat(destination)).size;
      }
      mapping['/' + path.relative(publicDir, source).split(path.sep).join('/')] =
        variants;
      before += bytes.length;
    }
  }),
);

const sorted = Object.fromEntries(
  Object.entries(mapping).sort(([a], [b]) => a.localeCompare(b)),
);
await writeFile(path.join(output, 'manifest.json'), JSON.stringify(sorted));
const current = new Set(
  Object.values(mapping).flatMap((variants) =>
    variants.map((variant) => path.basename(variant.url)),
  ),
);
for (const name of await readdir(output)) {
  if (name.endsWith('.webp') && !current.has(name))
    await unlink(path.join(output, name));
}

const source = `// Generated by scripts/optimize-images.mjs; do not edit.
export type ImageVariant = { width: number; url: string };

const optimizedImages: Record<string, ImageVariant[]> = ${JSON.stringify(sorted, null, 2)};

// Variants are also reachable by their own URL so a path that has already been
// resolved once — server components hand pre-resolved strings to the client —
// still finds its siblings.
const byVariantUrl = new Map<string, ImageVariant[]>();
for (const variants of Object.values(optimizedImages))
  for (const variant of variants) byVariantUrl.set(variant.url, variants);

function variantsFor(src: string): ImageVariant[] | undefined {
  const key = src.split('?')[0];
  return optimizedImages[key] ?? byVariantUrl.get(key);
}

/** The full-resolution WebP for a source path, or the path itself if unknown. */
export function imageSource(src: string) {
  const variants = variantsFor(src);
  return variants ? variants[variants.length - 1].url : src;
}

/**
 * Candidates for an <img>. \`displayWidth\` is the widest the element is ever
 * painted in CSS pixels; the browser multiplies it by the device pixel ratio
 * and takes the smallest candidate that still covers the result.
 */
export function imageSrcSet(src: string, displayWidth?: number) {
  const variants = variantsFor(src);
  if (!variants) return { src, srcSet: undefined, sizes: undefined };
  const largest = variants[variants.length - 1];
  return {
    src: largest.url,
    srcSet: variants.map((v) => \`\${v.url} \${v.width}w\`).join(', '),
    sizes: displayWidth ? \`\${displayWidth}px\` : undefined,
  };
}
`;
const manifest = path.join(root, 'lib/optimized-images.ts');
if ((await readFile(manifest, 'utf8').catch(() => '')) !== source)
  await writeFile(manifest, source);
console.log(
  `Images: ${files.length} sources, ${current.size} files; ${(before / 1e6).toFixed(1)} MB → ${(after / 1e6).toFixed(1)} MB.`,
);
