import {
  readdir,
  readFile,
  writeFile,
  mkdir,
  stat,
  unlink,
} from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = fileURLToPath(new URL('../', import.meta.url));
const publicDir = path.join(root, 'public');
const output = path.join(publicDir, 'optimized');
await mkdir(output, { recursive: true });
async function imagesIn(directory) {
  const result = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const filename = path.join(directory, entry.name);
    if (filename === output) continue;
    if (entry.isDirectory()) result.push(...(await imagesIn(filename)));
    else if (/\.(png|jpe?g)$/i.test(entry.name)) result.push(filename);
  }
  return result;
}
const files = (await imagesIn(publicDir)).sort();
const mapping = {};
let before = 0;
let after = 0;
let cursor = 0;
sharp.concurrency(2);
await Promise.all(
  Array.from({ length: 3 }, async () => {
    while (cursor < files.length) {
      const source = files[cursor++];
      const bytes = await readFile(source);
      const size = path.basename(source).startsWith('portrait-') ? 280 : 1400;
      const options = { quality: 88, alphaQuality: 100, effort: 4 };
      const digest = createHash('sha256')
        .update(JSON.stringify({ size, options, sharp: sharp.versions }))
        .update(bytes)
        .digest('hex')
        .slice(0, 16);
      const name = `${path.parse(source).name}-${digest}.webp`;
      const destination = path.join(output, name);
      try {
        await stat(destination);
      } catch {
        await sharp(bytes)
          .rotate()
          .resize({
            width: size,
            height: size,
            fit: 'inside',
            withoutEnlargement: true,
          })
          .webp(options)
          .toFile(destination);
      }
      mapping[
        '/' + path.relative(publicDir, source).split(path.sep).join('/')
      ] = '/optimized/' + name;
      before += bytes.length;
      after += (await stat(destination)).size;
    }
  }),
);
const sorted = Object.fromEntries(
  Object.entries(mapping).sort(([a], [b]) => a.localeCompare(b)),
);
await writeFile(path.join(output, 'manifest.json'), JSON.stringify(sorted));
const current = new Set(
  Object.values(mapping).map((url) => path.basename(url)),
);
for (const name of await readdir(output)) {
  if (name.endsWith('.webp') && !current.has(name))
    await unlink(path.join(output, name));
}
const source = `// Generated by scripts/optimize-images.mjs; do not edit.\nconst optimizedImages: Record<string, string> = ${JSON.stringify(sorted, null, 2)};\n\nexport function imageSource(src: string) {\n  return optimizedImages[src.split('?')[0]] ?? src;\n}\n`;
const manifest = path.join(root, 'lib/optimized-images.ts');
if ((await readFile(manifest, 'utf8').catch(() => '')) !== source)
  await writeFile(manifest, source);
console.log(
  `Images: ${files.length}; ${(before / 1e6).toFixed(1)} MB → ${(after / 1e6).toFixed(1)} MB (${Math.round(100 * (1 - after / before))}% smaller).`,
);
